Adding docker-compose
seatgeek/sixpack pull request #297
Opened 2019-01-15 01:38 UTC by stlimtat

Hi,
  I did a simple bunch of work to add Dockerfile-sixpack and docker-compose to simplify the deployment of a docker instance of the application.

  I hope you can add it to your repo.

2019-01-15 17:23 UTC, zackkitzmiller requested changes

2019-01-15 17:23 UTC, zackkitzmiller commented on README.rst
> +Getting Started WIth Docker
Small typo here. Capital I

2019-01-15 17:23 UTC, zackkitzmiller commented on config.yml
> -redis_host: localhost
Can you revert the changes to config.yml

2019-01-16 01:04 UTC, stlimtat reviewed
Fixed requested changes.

2019-01-16 07:41 UTC, stlimtat commented
Ok.  The fixes I think makes the system more generic are in.

TODO:
a. Config will read a file and does not allow the override of specific variables such as SIXPACK_CONFIG_REDIS_HOST to be done via environment which may be useful for deployments such as kubernetes type configuration.

2020-12-04 21:25 UTC, zackkitzmiller approved these changes
This looks good to me.

2025-08-25 13:18 UTC, closed without merging